---
- name: Calling GOL Deployment Role
  hosts: all
  #gather_facts: no
  become: yes
  pre_tasks:
    - name: Update Ubuntu package library
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - name: tomcat_role
      become: yes